title: Enygma Sistemas de Segurança
email: contato@enygmaalarmes.com.br
description: > 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://enygmaalarmes.com.br"

# Build settings
markdown: kramdown
exclude:
  - desktop.ini
  - gulpfile.js
  - README.md

sass:
  style: compressed

gems:
  - jekyll-coffeescript

collections:
  erros:
    output: true
  sections:
    output: false

defaults:
  - scope:
      path: ""
      type: erros
    values:
      layout: page
