title: Enygma Sistemas de Segurança
email: contato@enygmaalarmes.com.br
description: >
  Somos a sua empresa de segurança, especializada na instalação e
  manutenção de sistemas de segurança para a sua residência ou
  empresa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://enygmaalarmes.com.br"

# Build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-coffeescript

collections:
  erros:
    output: true
  sections:
    output: false

defaults:
  - scope:
      path: ""
      type: erros
    values:
      layout: page
